package vinos.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Desglose generated by hbm2java
 */
@Entity
@Table(name="desglose"
    ,catalog="tiendavinos"
)
public class Desglose  implements java.io.Serializable {

	private static final long serialVersionUID = 1841562088169722945L;
	private DesgloseId id;
     private Compra compra;
     private Ficha ficha;
     private Integer cantidad;

    public Desglose() {
    }

	
    public Desglose(DesgloseId id, Compra compra, Ficha ficha) {
        this.id = id;
        this.compra = compra;
        this.ficha = ficha;
    }
    public Desglose(DesgloseId id, Compra compra, Ficha ficha, Integer cantidad) {
       this.id = id;
       this.compra = compra;
       this.ficha = ficha;
       this.cantidad = cantidad;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="iddesglose", column=@Column(name="iddesglose", nullable=false) ), 
        @AttributeOverride(name="compraIdcompra", column=@Column(name="compra_idcompra", nullable=false) ), 
        @AttributeOverride(name="fichaIdficha", column=@Column(name="ficha_idficha", nullable=false) ) } )
    public DesgloseId getId() {
        return this.id;
    }
    
    public void setId(DesgloseId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="compra_idcompra", nullable=false, insertable=false, updatable=false)
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ficha_idficha", nullable=false, insertable=false, updatable=false)
    public Ficha getFicha() {
        return this.ficha;
    }
    
    public void setFicha(Ficha ficha) {
        this.ficha = ficha;
    }

    
    @Column(name="cantidad")
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }




}


