package vinos.model;
// Generated 14-feb-2017 11:53:08 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DesgloseId generated by hbm2java
 */
@Embeddable
public class DesgloseId  implements java.io.Serializable {

	private static final long serialVersionUID = 108113546793200480L;
	private int iddesglose;
    private int compraIdcompra;
    private int fichaIdficha;

    public DesgloseId() {
    }

    public DesgloseId(int iddesglose, int compraIdcompra, int fichaIdficha) {
       this.iddesglose = iddesglose;
       this.compraIdcompra = compraIdcompra;
       this.fichaIdficha = fichaIdficha;
    }
   


    @Column(name="iddesglose", nullable=false)
    public int getIddesglose() {
        return this.iddesglose;
    }
    
    public void setIddesglose(int iddesglose) {
        this.iddesglose = iddesglose;
    }


    @Column(name="compra_idcompra", nullable=false)
    public int getCompraIdcompra() {
        return this.compraIdcompra;
    }
    
    public void setCompraIdcompra(int compraIdcompra) {
        this.compraIdcompra = compraIdcompra;
    }


    @Column(name="ficha_idficha", nullable=false)
    public int getFichaIdficha() {
        return this.fichaIdficha;
    }
    
    public void setFichaIdficha(int fichaIdficha) {
        this.fichaIdficha = fichaIdficha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DesgloseId) ) return false;
		 DesgloseId castOther = ( DesgloseId ) other; 
         
		 return (this.getIddesglose()==castOther.getIddesglose())
 && (this.getCompraIdcompra()==castOther.getCompraIdcompra())
 && (this.getFichaIdficha()==castOther.getFichaIdficha());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIddesglose();
         result = 37 * result + this.getCompraIdcompra();
         result = 37 * result + this.getFichaIdficha();
         return result;
   }   


}


