package vinos.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Formapago generated by hbm2java
 */
@Entity
@Table(name="formapago"
    ,catalog="tiendavinos"
)
public class Formapago  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1253332086822366718L;
	private Integer idformaPago;
     private String nombre;
     private Integer porcentaje;
     private Set<Compra> compras = new HashSet<Compra>(0);

    public Formapago() {
    }

    public Formapago(String nombre, Integer porcentaje, Set<Compra> compras) {
       this.nombre = nombre;
       this.porcentaje = porcentaje;
       this.compras = compras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idformaPago", unique=true, nullable=false)
    public Integer getIdformaPago() {
        return this.idformaPago;
    }
    
    public void setIdformaPago(Integer idformaPago) {
        this.idformaPago = idformaPago;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="porcentaje")
    public Integer getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(Integer porcentaje) {
        this.porcentaje = porcentaje;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="formapago")
    public Set<Compra> getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set<Compra> compras) {
        this.compras = compras;
    }




}


