package vinos.model;
// Generated 14-feb-2017 11:53:08 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Valoraciones generated by hbm2java
 */
@Entity
@Table(name="valoraciones"
    ,catalog="tiendavinos"
)
public class Valoraciones  implements java.io.Serializable {


	private static final long serialVersionUID = -3850143408129882983L;
	private Integer idvaloraciones;
     private Ficha ficha;
     private Usuario usuario;
     private String comentario;
     private Integer valoracion;
     private Date fecha;

    public Valoraciones() {
    }

	
    public Valoraciones(Ficha ficha, Usuario usuario, Date fecha) {
        this.ficha = ficha;
        this.usuario = usuario;
        this.fecha = fecha;
    }
    public Valoraciones(Ficha ficha, Usuario usuario, String comentario, Integer valoracion, Date fecha) {
       this.ficha = ficha;
       this.usuario = usuario;
       this.comentario = comentario;
       this.valoracion = valoracion;
       this.fecha = fecha;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idvaloraciones", unique=true, nullable=false)
    public Integer getIdvaloraciones() {
        return this.idvaloraciones;
    }
    
    public void setIdvaloraciones(Integer idvaloraciones) {
        this.idvaloraciones = idvaloraciones;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ficha_idficha", nullable=false)
    public Ficha getFicha() {
        return this.ficha;
    }
    
    public void setFicha(Ficha ficha) {
        this.ficha = ficha;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_idusuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="comentario", length=250)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    
    @Column(name="valoracion")
    public Integer getValoracion() {
        return this.valoracion;
    }
    
    public void setValoracion(Integer valoracion) {
        this.valoracion = valoracion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


