package vinos.model;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Zona generated by hbm2java
 */
@Entity
@Table(name="zona"
    ,catalog="tiendavinos"
)
public class Zona  implements java.io.Serializable {

	private static final long serialVersionUID = -6704570833355827858L;
	private Integer idzona;
     private String zona;
     private Set<Bodega> bodegas = new HashSet<Bodega>(0);

    public Zona() {
    }

    public Zona(String zona, Set<Bodega> bodegas) {
       this.zona = zona;
       this.bodegas = bodegas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idzona", unique=true, nullable=false)
    public Integer getIdzona() {
        return this.idzona;
    }
    
    public void setIdzona(Integer idzona) {
        this.idzona = idzona;
    }

    
    @Column(name="zona", length=45)
    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="zona")
    public Set<Bodega> getBodegas() {
        return this.bodegas;
    }
    
    public void setBodegas(Set<Bodega> bodegas) {
        this.bodegas = bodegas;
    }




}


